title: Leonel Alejandro Salazar Ramirez
description: Senior Full Stack Developer | AI & Cloud-native Applications
theme: jekyll-theme-slate
show_downloads: false
google_analytics: 
plugins:
  - jekyll-seo-tag
